import {Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Navbar></Navbar>
        
        
        {children}
      </body>
    </html>
  );
}
